rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-1.7.12
  - rbx-2.5.7

# whitelist
branches:
  only:
    - master
    - v1.3.x-bugfix
    - add-rubinius-support

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
